APPLICATION_VERSION="20230101-SNAPSHOT"
ROOT_FOLDER="${HOME}/java-exam-evaluator"
export JAVA_EXAM_EVALUATOR_JAR="${ROOT_FOLDER}/evaluator/java-exam-evaluator-${APPLICATION_VERSION}.jar"
export JAVA_EXAM_VALIDATOR_JAR="${ROOT_FOLDER}/validator/java-exam-validator-${APPLICATION_VERSION}.jar"
export JAVA_HOME="/Library/Java/JavaVirtualMachines/openjdk-17.jdk/Contents/Home"